virtual-storage:
  # Determines if virtual storage is enabled by default for new spawners.
  # Set to false if you prefer no virtual storage on newly placed spawners.
  default: true

  # If set to true, the default value cannot be changed by players.
  force-default: false

  # Permission required for players to toggle virtual storage on their spawners.
  permission: ancspawners.settings.togglestorage

xp-storage:
  # Determines if XP storage is enabled by default for new spawners.
  default: true

  # If set to true, the default value can not be changed by players.
  force-default: false

  # Permission required for players to toggle XP storage on their spawners.
  permission: ancspawners.settings.togglexp
